# Generated by Django 5.1 on 2026-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'card'), ('transfer', 'transfer')], default='card', max_length=20),
        ),
    ]
