# Generated by Django 5.1 on 2026-01-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('payment_link_created', 'Link de pago creado'), ('pending_transfer', 'Pendiente (transferencia)'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=30),
        ),
    ]
