# Generated by Django 5.1 on 2026-01-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('payment_link_created', 'Link de pago creado'), ('paid', 'Pagada'), ('processing', 'En proceso'), ('shipped', 'Enviada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=30),
        ),
    ]
