# Generated by Django 5.1 on 2026-01-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_variant_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.variant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='compare_at',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
